[tool.poetry]
name = "reinforsment learning"
version = "0.1.0"
description = ""
authors = ["Daniil <122814306+Qwest1204@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
notebook = "^7.2.2"
torch = "2.4.0"
numpy = "1.24.1"
gym = {version = "0.12.5", extras = ["atary"]}
pyglet = "1.5.27"
matplotlib = "^3.9.2"
gymnasium = {extras = ["box2d"], version = "^0.29.1"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "torch118"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"