[tool.poetry]
name = "reinforsment learning"
version = "0.1.0"
description = ""
authors = ["Daniil <122814306+Qwest1204@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
notebook = "^7.2.2"
numpy = "1.24.1"
pyglet = "1.5.27"
matplotlib = "^3.9.2"
gymnasium = {extras = ["all"], version = "^0.29.1"}
gym-super-mario-bros = "7.4.0"
tensordict = "^0.5.0"
torch = { url = "https://download.pytorch.org/whl/cu118/torch-2.4.0%2Bcu118-cp310-cp310-win_amd64.whl"}
torchrl = "^0.5.0"
torchvision = "^0.19.0"
autorom = {extras = ["accept-rom-license"], version = "^0.6.1"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
